# Generated by Django 4.1.2 on 2022-10-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='city',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='country',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='imageType',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='state',
        ),
        migrations.AddField(
            model_name='satellite',
            name='satelliteID',
            field=models.CharField(choices=[('15', 'Sat 15'), ('18', 'Sat 18'), ('19', 'Sat 19')], default='15', max_length=2),
        ),
    ]
