# Generated by Django 4.1.2 on 2022-10-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite', '0002_remove_satellite_city_remove_satellite_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='image',
            field=models.ImageField(upload_to='satellite/'),
        ),
    ]
